package com.solutionium.sharedui.designsystem.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFF15C34)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFE3DA)
val onPrimaryContainerLight = Color(0xFF4A1406)
val secondaryLight = Color(0xFF8A4E3F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDDD2)
val onSecondaryContainerLight = Color(0xFF341710)
val tertiaryLight = Color(0xFF6C5C3E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF5E6BE)
val onTertiaryContainerLight = Color(0xFF251B05)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFCFAF8)
val onBackgroundLight = Color(0xFF1D1B19)
val surfaceLight = Color(0xFFFCFAF8)
val onSurfaceLight = Color(0xFF1D1B19)
val surfaceVariantLight = Color(0xFFEDE4DF)
val onSurfaceVariantLight = Color(0xFF514944)
val outlineLight = Color(0xFF83766F)
val outlineVariantLight = Color(0xFFD4CAC4)
val scrimLight = Color(0x66000000)
val inverseSurfaceLight = Color(0xFF322F2D)
val inverseOnSurfaceLight = Color(0xFFF6F0EC)
val inversePrimaryLight = Color(0xFFFFB9A5)
val surfaceDimLight = Color(0xFFDDD8D4)
val surfaceBrightLight = Color(0xFFFCFAF8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F3EF)
val surfaceContainerLight = Color(0xFFF2EDE8)
val surfaceContainerHighLight = Color(0xFFECE6E2)
val surfaceContainerHighestLight = Color(0xFFE6E1DC)


val primaryDark = Color(0xFFFFB9A5)
val onPrimaryDark = Color(0xFF5A1A09)
val primaryContainerDark = Color(0xFFB84B2D)
val onPrimaryContainerDark = Color(0xFFFFDED2)
val secondaryDark = Color(0xFFE8BCAF)
val onSecondaryDark = Color(0xFF44261E)
val secondaryContainerDark = Color(0xFF5A3A31)
val onSecondaryContainerDark = Color(0xFFFFDDD2)
val tertiaryDark = Color(0xFFD8C691)
val onTertiaryDark = Color(0xFF3C3010)
val tertiaryContainerDark = Color(0xFF564723)
val onTertiaryContainerDark = Color(0xFFF4E2AB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF151312)
val onBackgroundDark = Color(0xFFE8E2DE)
val surfaceDark = Color(0xFF151312)
val onSurfaceDark = Color(0xFFE8E2DE)
val surfaceVariantDark = Color(0xFF4F4642)
val onSurfaceVariantDark = Color(0xFFD2C8C2)
val outlineDark = Color(0xFF9C9088)
val outlineVariantDark = Color(0xFF4F4642)
val scrimDark = Color(0x99000000)
val inverseSurfaceDark = Color(0xFFE8E2DE)
val inverseOnSurfaceDark = Color(0xFF322F2D)
val inversePrimaryDark = Color(0xFFF15C34)
val surfaceDimDark = Color(0xFF151312)
val surfaceBrightDark = Color(0xFF3C3835)
val surfaceContainerLowestDark = Color(0xFF100E0D)
val surfaceContainerLowDark = Color(0xFF1D1A18)
val surfaceContainerDark = Color(0xFF211E1B)
val surfaceContainerHighDark = Color(0xFF2C2825)
val surfaceContainerHighestDark = Color(0xFF373330)








